import dns from 'dns';
import mongoose from 'mongoose';
import env from '../config/env.config.js';
import Product from '../models/Product.model.js';

if (env.MONGO_URI.startsWith('mongodb+srv://')) {
  try {
    dns.setServers(['8.8.8.8', '8.8.4.4']);
  } catch (dnsErr) {
    console.warn('[MongoDB] Warning: Could not override DNS servers:', dnsErr.message);
  }
}

const additionalProducts = [
  // Laptops (10 products)
  {
    name: 'Apple MacBook Air 15-inch M3 Chip',
    category: 'laptops',
    brand: 'Apple',
    price: 134900,
    mrp: 144900,
    rating: 4.9,
    numReviews: 248,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    description: 'Impossibly thin and fast with 18-hour battery life, Liquid Retina display, and the powerful M3 chip.',
  },
  {
    name: 'Dell XPS 15 OLED InfinityEdge Laptop',
    category: 'laptops',
    brand: 'Dell',
    price: 169990,
    mrp: 189990,
    rating: 4.8,
    numReviews: 184,
    image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80',
    description: 'Intel Core i7 13th Gen, 3.5K OLED touchscreen, CNC machined aluminum chassis with carbon fiber palm rest.',
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon Gen 11',
    category: 'laptops',
    brand: 'Lenovo',
    price: 154990,
    mrp: 172990,
    rating: 4.8,
    numReviews: 120,
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
    description: 'Ultralight carbon-fiber business flagship with Intel Evo vPro, Dolby Atmos speaker system, and legendary keyboard.',
  },
  {
    name: 'ASUS ROG Zephyrus G16 Gaming Laptop',
    category: 'laptops',
    brand: 'ASUS',
    price: 179990,
    mrp: 199990,
    rating: 4.7,
    numReviews: 142,
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80',
    description: '240Hz OLED ROG Nebula display, NVIDIA RTX 4070 8GB graphics, ultra-thin CNC aluminum unibody.',
  },
  {
    name: 'HP Spectre x360 2-in-1 Convertible Laptop',
    category: 'laptops',
    brand: 'HP',
    price: 142990,
    mrp: 159990,
    rating: 4.7,
    numReviews: 95,
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80',
    description: 'Versatile 360-degree hinge, 2.8K OLED HDR touch display, AI-enhanced 9MP webcam, and magnetic stylus pen.',
  },
  {
    name: 'Razer Blade 14 Compact Gaming Rig',
    category: 'laptops',
    brand: 'Razer',
    price: 199990,
    mrp: 224990,
    rating: 4.9,
    numReviews: 110,
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&auto=format&fit=crop&q=80',
    description: 'AMD Ryzen 9 8945HS, RTX 4070, QHD+ 240Hz display encased in anodized matte black aluminum.',
  },
  {
    name: 'Microsoft Surface Laptop Studio 2',
    category: 'laptops',
    brand: 'Microsoft',
    price: 184990,
    mrp: 204990,
    rating: 4.6,
    numReviews: 76,
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80',
    description: 'Dynamic woven hinge transforms laptop into studio canvas, PixelSense Flow touch display with Slim Pen 2.',
  },
  {
    name: 'Acer Swift Go 14 AI OLED Laptop',
    category: 'laptops',
    brand: 'Acer',
    price: 79990,
    mrp: 89990,
    rating: 4.5,
    numReviews: 88,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80',
    description: 'Intel Core Ultra 7 with built-in NPU for AI workloads, 2.8K 90Hz OLED 100% DCI-P3 display.',
  },
  {
    name: 'Framework Laptop 13 Modular Edition',
    category: 'laptops',
    brand: 'Framework',
    price: 112990,
    mrp: 125990,
    rating: 4.8,
    numReviews: 64,
    image: 'https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=800&auto=format&fit=crop&q=80',
    description: 'Fully repairable and modular ultraportable with swappable expansion cards and customizable ports.',
  },
  {
    name: 'Samsung Galaxy Book4 Pro 360',
    category: 'laptops',
    brand: 'Samsung',
    price: 163990,
    mrp: 179990,
    rating: 4.7,
    numReviews: 92,
    image: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&auto=format&fit=crop&q=80',
    description: 'Dynamic AMOLED 2X touchscreen with Anti-Reflective coating, S Pen included, seamless Galaxy ecosystem sync.',
  },

  // Smartphones (10 products)
  {
    name: 'Apple iPhone 15 Pro Max 256GB Natural Titanium',
    category: 'smartphones',
    brand: 'Apple',
    price: 154900,
    mrp: 159900,
    rating: 4.9,
    numReviews: 430,
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
    description: 'Aerospace-grade titanium design, A17 Pro chip, 5x Telephoto optical zoom, and customizable Action button.',
  },
  {
    name: 'Samsung Galaxy S24 Ultra 5G AI Phone',
    category: 'smartphones',
    brand: 'Samsung',
    price: 129999,
    mrp: 139999,
    rating: 4.8,
    numReviews: 380,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
    description: 'Titanium frame, Galaxy AI live translate, 200MP quad-telephoto camera system, and integrated S Pen stylus.',
  },
  {
    name: 'Google Pixel 8 Pro with Gemini Nano',
    category: 'smartphones',
    brand: 'Google',
    price: 98999,
    mrp: 106999,
    rating: 4.7,
    numReviews: 210,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80',
    description: 'Google Tensor G3, pro camera controls, Magic Editor, thermometer sensor, and 7 years of OS updates.',
  },
  {
    name: 'OnePlus 12 5G Flowy Emerald 16GB RAM',
    category: 'smartphones',
    brand: 'OnePlus',
    price: 69999,
    mrp: 74999,
    rating: 4.8,
    numReviews: 295,
    image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800&auto=format&fit=crop&q=80',
    description: 'Snapdragon 8 Gen 3, 4th Gen Hasselblad camera, 2K 120Hz ProXDR display, and 100W SUPERVOOC flash charging.',
  },
  {
    name: 'Nothing Phone (2) Glyph Interface 256GB',
    category: 'smartphones',
    brand: 'Nothing',
    price: 37999,
    mrp: 44999,
    rating: 4.6,
    numReviews: 185,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80',
    description: 'Iconic transparent back with customizable LED Glyph lighting, Snapdragon 8+ Gen 1, and Nothing OS 2.5.',
  },
  {
    name: 'Xiaomi 14 Ultra Leica Summilux Edition',
    category: 'smartphones',
    brand: 'Xiaomi',
    price: 99999,
    mrp: 119999,
    rating: 4.8,
    numReviews: 130,
    image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80',
    description: 'Quad 50MP Leica optical lenses with 1-inch Sony LYT-900 sensor and stepless variable aperture f/1.63-f/4.0.',
  },
  {
    name: 'Vivo X100 Pro Zeiss APO Telephoto',
    category: 'smartphones',
    brand: 'Vivo',
    price: 89999,
    mrp: 96999,
    rating: 4.7,
    numReviews: 115,
    image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80',
    description: 'Zeiss APO Floating Telephoto camera, MediaTek Dimensity 9300 chipset, and V3 imaging coprocessor chip.',
  },
  {
    name: 'Motorola Edge 50 Ultra Pantone Peach Fuzz',
    category: 'smartphones',
    brand: 'Motorola',
    price: 54999,
    mrp: 64999,
    rating: 4.6,
    numReviews: 98,
    image: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&auto=format&fit=crop&q=80',
    description: 'Real wood & vegan leather rear finishes, 144Hz pOLED curved screen, 125W TurboPower and 50W wireless charging.',
  },
  {
    name: 'Realme GT 6 AI Flagship Killer',
    category: 'smartphones',
    brand: 'Realme',
    price: 40999,
    mrp: 44999,
    rating: 4.5,
    numReviews: 160,
    image: 'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800&auto=format&fit=crop&q=80',
    description: 'Ultra-bright 6000 nits LTPO AMOLED display, Snapdragon 8s Gen 3, Sony LYT-808 OIS main camera.',
  },
  {
    name: 'Asus ROG Phone 8 Pro Gaming Smartphone',
    category: 'smartphones',
    brand: 'Asus',
    price: 94999,
    mrp: 104999,
    rating: 4.8,
    numReviews: 82,
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&auto=format&fit=crop&q=80',
    description: 'AniMe Vision programmable mini-LED back display, AirTrigger ultrasonic buttons, and IP68 waterproof rating.',
  },

  // Mobile Accessories (10 products)
  {
    name: 'Anker Prime 100W GaN Wall Fast Charger',
    category: 'mobile-accessories',
    brand: 'Anker',
    price: 4999,
    mrp: 6999,
    rating: 4.9,
    numReviews: 310,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    description: 'Ultra-compact 3-port fast charger with ActiveShield 2.0 temperature monitoring for MacBooks, iPads, and phones.',
  },
  {
    name: 'Belkin BoostCharge Pro 3-in-1 MagSafe Stand',
    category: 'mobile-accessories',
    brand: 'Belkin',
    price: 12999,
    mrp: 14999,
    rating: 4.8,
    numReviews: 175,
    image: 'https://images.unsplash.com/photo-1622445268046-6b22fa45e317?w=800&auto=format&fit=crop&q=80',
    description: 'Official 15W fast wireless charging for iPhone, Apple Watch fast charger, and AirPods Qi charging base.',
  },
  {
    name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    category: 'mobile-accessories',
    brand: 'Sony',
    price: 28990,
    mrp: 34990,
    rating: 4.9,
    numReviews: 540,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    description: 'Industry-leading noise cancellation with two processors and 8 microphones, LDAC Hi-Res Audio, 30-hour battery.',
  },
  {
    name: 'Bose QuietComfort Ultra Spatial Audio Earbuds',
    category: 'mobile-accessories',
    brand: 'Bose',
    price: 24999,
    mrp: 27999,
    rating: 4.8,
    numReviews: 220,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    description: 'Breakthrough spatialized audio with CustomTune sound calibration and world-class active noise cancelling.',
  },
  {
    name: 'Baseus Blade 100W 20000mAh Ultra-Thin Power Bank',
    category: 'mobile-accessories',
    brand: 'Baseus',
    price: 5499,
    mrp: 7499,
    rating: 4.7,
    numReviews: 165,
    image: 'https://images.unsplash.com/photo-1609592424361-b924b176cfbd?w=800&auto=format&fit=crop&q=80',
    description: 'Slim laptop-friendly battery pack with digital status screen showing charging speed, voltage, and remaining time.',
  },
  {
    name: 'Spigen Tough Armor MagFit Case for iPhone',
    category: 'mobile-accessories',
    brand: 'Spigen',
    price: 2299,
    mrp: 2999,
    rating: 4.8,
    numReviews: 410,
    image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&auto=format&fit=crop&q=80',
    description: 'Air Cushion technology with shock-absorbing foam layer, reinforced kickstand, and strong magnetic snap.',
  },
  {
    name: 'Peak Design Mobile Everyday Phone Mount with SlimLink',
    category: 'mobile-accessories',
    brand: 'Peak Design',
    price: 6499,
    mrp: 7499,
    rating: 4.9,
    numReviews: 95,
    image: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=800&auto=format&fit=crop&q=80',
    description: 'Machined/anodized aluminum magnetic motorcycle and car mount with ball-head vibration damper.',
  },
  {
    name: 'UGREEN 40Gbps Thunderbolt 4 Braided Cable (1m)',
    category: 'mobile-accessories',
    brand: 'UGREEN',
    price: 2499,
    mrp: 3299,
    rating: 4.8,
    numReviews: 180,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    description: 'Certified 240W Power Delivery and 8K video output with heavy-duty nylon braided exterior and aluminum connectors.',
  },
  {
    name: 'Nomad Rugged Horween Leather MagSafe Case',
    category: 'mobile-accessories',
    brand: 'Nomad',
    price: 4999,
    mrp: 5999,
    rating: 4.7,
    numReviews: 130,
    image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&auto=format&fit=crop&q=80',
    description: 'Sustainably sourced American Horween leather that develops a rich, individual patina over months of use.',
  },
  {
    name: 'DJI Osmo Mobile 6 Handheld Smartphone Gimbal',
    category: 'mobile-accessories',
    brand: 'DJI',
    price: 13490,
    mrp: 15990,
    rating: 4.8,
    numReviews: 190,
    image: 'https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=800&auto=format&fit=crop&q=80',
    description: '3-axis stabilization with ActiveTrack 6.0 subject tracking, built-in extension rod, and magnetic phone clamp.',
  },

  // Mens Watches (10 products)
  {
    name: 'Seiko Presage Cocktail Time Automatic Watch',
    category: 'mens-watches',
    brand: 'Seiko',
    price: 39500,
    mrp: 44000,
    rating: 4.9,
    numReviews: 145,
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&auto=format&fit=crop&q=80',
    description: 'Sunburst textured ice-blue dial inspired by artisan Tokyo cocktails, Caliber 4R35 automatic movement, exhibition caseback.',
  },
  {
    name: 'Tissot PRX Powermatic 80 Blue Dial',
    category: 'mens-watches',
    brand: 'Tissot',
    price: 66000,
    mrp: 72000,
    rating: 4.9,
    numReviews: 230,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
    description: 'Integrated 1970s stainless steel bracelet with waffle tapisserie dial, 80-hour power reserve, Nivachron balance spring.',
  },
  {
    name: 'Casio G-Shock GA-B2100 Tough Solar Bluetooth',
    category: 'mens-watches',
    brand: 'Casio',
    price: 11995,
    mrp: 13995,
    rating: 4.8,
    numReviews: 380,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    description: 'Octagonal "CasiOak" carbon core guard, solar-powered battery, Bluetooth smartphone time calibration, 200m water resistance.',
  },
  {
    name: 'Citizen Eco-Drive Promaster Diver 200M',
    category: 'mens-watches',
    brand: 'Citizen',
    price: 29500,
    mrp: 33000,
    rating: 4.7,
    numReviews: 160,
    image: 'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=800&auto=format&fit=crop&q=80',
    description: 'ISO-compliant dive watch powered by any light source, never needs a battery change, unidirectional rotating bezel.',
  },
  {
    name: 'Hamilton Khaki Field Mechanical 38mm',
    category: 'mens-watches',
    brand: 'Hamilton',
    price: 49500,
    mrp: 55000,
    rating: 4.9,
    numReviews: 110,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
    description: 'Original military army heritage timepiece, manual-wind H-50 movement with 80 hours power reserve and durable NATO canvas strap.',
  },
  {
    name: 'Fossil Neutra Minimalist Chronograph Watch',
    category: 'mens-watches',
    brand: 'Fossil',
    price: 12495,
    mrp: 14995,
    rating: 4.5,
    numReviews: 215,
    image: 'https://images.unsplash.com/photo-1526045478516-99145907023c?w=800&auto=format&fit=crop&q=80',
    description: 'Clean mid-century architecture dial, genuine amber leather strap, three-hand sub-dial stopwatch stopwatch functions.',
  },
  {
    name: 'Garmin Fenix 7 Pro Sapphire Solar Multi-Sport Watch',
    category: 'mens-watches',
    brand: 'Garmin',
    price: 84990,
    mrp: 96990,
    rating: 4.9,
    numReviews: 175,
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
    description: 'Built-in LED flashlight, multi-band GPS with SatIQ, HRV tracking, TopoActive maps, and up to 37 days battery life with solar.',
  },
  {
    name: 'Apple Watch Ultra 2 Titanium 49mm GPS + Cellular',
    category: 'mens-watches',
    brand: 'Apple',
    price: 89900,
    mrp: 89900,
    rating: 4.9,
    numReviews: 290,
    image: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&auto=format&fit=crop&q=80',
    description: '3000-nit retina display, S9 SiP with Double Tap gesture, precision dual-frequency GPS, depth gauge for recreational scuba.',
  },
  {
    name: 'Timex Marlin Automatic California Dial 40mm',
    category: 'mens-watches',
    brand: 'Timex',
    price: 21995,
    mrp: 24995,
    rating: 4.6,
    numReviews: 95,
    image: 'https://images.unsplash.com/photo-1547996160-71dfa63595aa?w=800&auto=format&fit=crop&q=80',
    description: 'Domed acrylic crystal, vintage Roman/Arabic California numerals, 21-jewel Japanese mechanical movement.',
  },
  {
    name: 'Orient Bambino Version IV Classic Dress Watch',
    category: 'mens-watches',
    brand: 'Orient',
    price: 18900,
    mrp: 22000,
    rating: 4.8,
    numReviews: 180,
    image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80',
    description: 'Classic domed dial with ombré gradient emerald finish, hand-winding and hacking automatic caliber, suede leather band.',
  },

  // Tablets (10 products)
  {
    name: 'Apple iPad Pro 13-inch M4 Ultra Retina XDR',
    category: 'tablets',
    brand: 'Apple',
    price: 129900,
    mrp: 129900,
    rating: 4.9,
    numReviews: 190,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
    description: 'Thinnest Apple product ever at 5.1mm, Tandem OLED breakthrough display, M4 neural engine, supports Apple Pencil Pro.',
  },
  {
    name: 'Samsung Galaxy Tab S9 Ultra 14.6-inch Dynamic AMOLED',
    category: 'tablets',
    brand: 'Samsung',
    price: 108999,
    mrp: 121999,
    rating: 4.8,
    numReviews: 165,
    image: 'https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=800&auto=format&fit=crop&q=80',
    description: 'IP68 water/dust resistant tablet with bundled low-latency S Pen, Snapdragon 8 Gen 2 for Galaxy, quad AKG speakers.',
  },
  {
    name: 'Apple iPad Air 11-inch M2 Liquid Retina',
    category: 'tablets',
    brand: 'Apple',
    price: 59900,
    mrp: 59900,
    rating: 4.8,
    numReviews: 240,
    image: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&auto=format&fit=crop&q=80',
    description: 'Blazing-fast M2 chip performance, landscape 12MP Center Stage front camera, all-day battery life in stunning starlight.',
  },
  {
    name: 'Xiaomi Pad 6 Pro 11-inch 144Hz WQHD+',
    category: 'tablets',
    brand: 'Xiaomi',
    price: 28999,
    mrp: 34999,
    rating: 4.7,
    numReviews: 210,
    image: 'https://images.unsplash.com/photo-1527698266440-12104e498b76?w=800&auto=format&fit=crop&q=80',
    description: 'Snapdragon 870 powerhouse, 144Hz 7-stage refresh rate, quad stereo speakers with Dolby Vision Atmos, metal unibody.',
  },
  {
    name: 'OnePlus Pad 2 3K 144Hz ReadFit Display',
    category: 'tablets',
    brand: 'OnePlus',
    price: 39999,
    mrp: 44999,
    rating: 4.7,
    numReviews: 130,
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    description: 'Unique 7:5 aspect ratio optimized for reading and productivity, Snapdragon 8 Gen 3, 67W fast charging with 9510mAh battery.',
  },
  {
    name: 'Lenovo Tab P12 Pro AMOLED with Precision Pen 3',
    category: 'tablets',
    brand: 'Lenovo',
    price: 49990,
    mrp: 59990,
    rating: 4.6,
    numReviews: 85,
    image: 'https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=800&auto=format&fit=crop&q=80',
    description: '12.6-inch 2K AMOLED HDR10+ display, JBL quad-channel speakers, wireless second-screen capability for Windows PCs.',
  },
  {
    name: 'reMarkable 2 Digital Paper Tablet',
    category: 'tablets',
    brand: 'reMarkable',
    price: 42999,
    mrp: 47999,
    rating: 4.9,
    numReviews: 110,
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    description: 'Distraction-free Canvas display with real paper friction and texture, weeks-long battery life, instant cloud sync.',
  },
  {
    name: 'Amazon Kindle Scribe 10.2-inch Digital Notebook',
    category: 'tablets',
    brand: 'Amazon',
    price: 33999,
    mrp: 38999,
    rating: 4.7,
    numReviews: 170,
    image: 'https://images.unsplash.com/photo-1507842229451-79b1be886a20?w=800&auto=format&fit=crop&q=80',
    description: 'First Kindle for reading and writing, glare-free 300 ppi front-lit display, battery-free Basic Pen included.',
  },
  {
    name: 'Samsung Galaxy Tab S9 FE Water Resistant Tablet',
    category: 'tablets',
    brand: 'Samsung',
    price: 34999,
    mrp: 42999,
    rating: 4.6,
    numReviews: 140,
    image: 'https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?w=800&auto=format&fit=crop&q=80',
    description: 'Vision Booster adaptive brightness up to 600 nits, IP68 rated S Pen included in the box, expandable microSD storage up to 1TB.',
  },
  {
    name: 'Apple iPad 10th Gen 10.9-inch Liquid Retina',
    category: 'tablets',
    brand: 'Apple',
    price: 34900,
    mrp: 39900,
    rating: 4.7,
    numReviews: 320,
    image: 'https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=800&auto=format&fit=crop&q=80',
    description: 'All-screen colorful design, A14 Bionic chip, landscape stereo speakers, USB-C connectivity, Magic Keyboard Folio support.',
  },

  // Sunglasses (10 products)
  {
    name: 'Ray-Ban Wayfarer Classic Polarized Sunglasses',
    category: 'sunglasses',
    brand: 'Ray-Ban',
    price: 9890,
    mrp: 11500,
    rating: 4.9,
    numReviews: 320,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80',
    description: 'Timeless acetate icon worn since 1952, crystal green G-15 polarized lenses with 100% UV400 radiation protection.',
  },
  {
    name: 'Oakley Holbrook Prizm Black Polarized Lenses',
    category: 'sunglasses',
    brand: 'Oakley',
    price: 11290,
    mrp: 13400,
    rating: 4.8,
    numReviews: 215,
    image: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=800&auto=format&fit=crop&q=80',
    description: 'O-Matter stress-resistant lightweight frame with metal rivets and Prizm lens technology designed to enhance color and contrast.',
  },
  {
    name: 'Persol 714 Steve McQueen Folding Aviator Shades',
    category: 'sunglasses',
    brand: 'Persol',
    price: 24500,
    mrp: 28000,
    rating: 4.9,
    numReviews: 88,
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80',
    description: 'Handmade Italian folding sunglasses with Meflecto flexible stem system, patented crystal blue mirrored polarized lenses.',
  },
  {
    name: 'Maui Jim Ho’okipa PolarizedPlus2 Rimless Sunglasses',
    category: 'sunglasses',
    brand: 'Maui Jim',
    price: 16900,
    mrp: 19500,
    rating: 4.9,
    numReviews: 140,
    image: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800&auto=format&fit=crop&q=80',
    description: 'Featherlight rimless Grilamid frame with Hawaii Lava mirror lenses that eliminate 99.9% of glare and block harmful HEV light.',
  },
  {
    name: 'Tom Ford Snowdon Square Vintage Sunglasses',
    category: 'sunglasses',
    brand: 'Tom Ford',
    price: 28000,
    mrp: 32000,
    rating: 4.8,
    numReviews: 65,
    image: 'https://images.unsplash.com/photo-1509695507497-903c140c43b0?w=800&auto=format&fit=crop&q=80',
    description: 'Bold Havana acetate frame featuring the signature metal T logo on temples, gradient brown anti-reflective lenses.',
  },
  {
    name: 'Carrera Champion Pilot Teardrop Eyewear',
    category: 'sunglasses',
    brand: 'Carrera',
    price: 7990,
    mrp: 9500,
    rating: 4.6,
    numReviews: 175,
    image: 'https://images.unsplash.com/photo-1577803645773-f96470509666?w=800&auto=format&fit=crop&q=80',
    description: 'Motorsport-inspired Optyl memory plastic aviators with signature C monogram bridge detail and polycarbonate UV lenses.',
  },
  {
    name: 'Police Origins Bullet Matte Gunmetal Sunglasses',
    category: 'sunglasses',
    brand: 'Police',
    price: 8490,
    mrp: 10200,
    rating: 4.5,
    numReviews: 120,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80',
    description: 'Sleek metal double-bridge aviator frame with spring hinges and smoke blue gradient polarized mirror coatings.',
  },
  {
    name: 'Fastrack Polarized Rectangular Sports Eyewear',
    category: 'sunglasses',
    brand: 'Fastrack',
    price: 2495,
    mrp: 3195,
    rating: 4.4,
    numReviews: 280,
    image: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=800&auto=format&fit=crop&q=80',
    description: 'Durable wraparound TR90 frame with rubber nose pads for slip-free grip during cycling, driving, and running.',
  },
  {
    name: 'Prada Linea Rossa Lifestyle Mirror Sunglasses',
    category: 'sunglasses',
    brand: 'Prada',
    price: 22500,
    mrp: 26000,
    rating: 4.8,
    numReviews: 78,
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80',
    description: 'Red stripe sports luxury aesthetic with silver mirrored hydrophobic lenses and ultra-comfortable rubberized temple tips.',
  },
  {
    name: 'Lenskart Vincent Chase polarized Wayfarer',
    category: 'sunglasses',
    brand: 'Vincent Chase',
    price: 1499,
    mrp: 2499,
    rating: 4.5,
    numReviews: 350,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80',
    description: 'Lightweight everyday matte black frame with TAC polarized lenses, ideal for daily motorcycle commutes and outdoor bright sunlight.',
  },

  // Sports Accessories (10 products)
  {
    name: 'Nivia Storm Football Thermofused Size 5',
    category: 'sports-accessories',
    brand: 'Nivia',
    price: 1249,
    mrp: 1799,
    rating: 4.8,
    numReviews: 290,
    image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&auto=format&fit=crop&q=80',
    description: 'FIFA Pro standard 32-panel thermobonded seamless ball with butyl bladder for superior air retention and flight stability.',
  },
  {
    name: 'Yonex Astrox 99 Pro Badminton Racket 4U',
    category: 'sports-accessories',
    brand: 'Yonex',
    price: 15990,
    mrp: 18500,
    rating: 4.9,
    numReviews: 180,
    image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&auto=format&fit=crop&q=80',
    description: 'Rotational Generator System with Namd graphite in the shaft, delivers overwhelming smash power and steep attack angles.',
  },
  {
    name: 'Cosco Light Weight English Willow Cricket Bat',
    category: 'sports-accessories',
    brand: 'Cosco',
    price: 8499,
    mrp: 10999,
    rating: 4.7,
    numReviews: 140,
    image: 'https://images.unsplash.com/photo-1531415074868-036b107e775a?w=800&auto=format&fit=crop&q=80',
    description: 'Handcrafted Grade 2 English willow with thick 38mm edges, massive sweet spot, and multi-piece cane handle for shock absorption.',
  },
  {
    name: 'Spalding NBA Gold Series Indoor/Outdoor Basketball',
    category: 'sports-accessories',
    brand: 'Spalding',
    price: 2999,
    mrp: 3799,
    rating: 4.8,
    numReviews: 215,
    image: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=800&auto=format&fit=crop&q=80',
    description: 'Deep channel design composite leather with supreme tack and grip, suitable for both hardwood indoor courts and blacktop tarmac.',
  },
  {
    name: 'Boldfit Heavy Duty Resistance Bands Set of 5',
    category: 'sports-accessories',
    brand: 'Boldfit',
    price: 1499,
    mrp: 2499,
    rating: 4.7,
    numReviews: 450,
    image: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800&auto=format&fit=crop&q=80',
    description: '100% natural Malaysian latex loop bands with door anchor, foam handles, and ankle straps for full-body home workouts.',
  },
  {
    name: 'Kobo Cast Iron Adjustable Dumbbell Set 20KG',
    category: 'sports-accessories',
    brand: 'Kobo',
    price: 4999,
    mrp: 6999,
    rating: 4.6,
    numReviews: 195,
    image: 'https://images.unsplash.com/photo-1586401100454-05cb9bcf5cb8?w=800&auto=format&fit=crop&q=80',
    description: 'Heavy duty solid cast iron weight plates with spinlock collars and ergonomic textured chrome grip handles.',
  },
  {
    name: 'Strauss Anti-Skid Yoga Mat 6mm with Carry Strap',
    category: 'sports-accessories',
    brand: 'Strauss',
    price: 999,
    mrp: 1499,
    rating: 4.7,
    numReviews: 380,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&auto=format&fit=crop&q=80',
    description: 'High-density eco-friendly TPE foam with moisture-resistant dual-sided non-slip texture for cushioning joints during practice.',
  },
  {
    name: 'Speedo Fastskin Elite Mirror Competition Goggles',
    category: 'sports-accessories',
    brand: 'Speedo',
    price: 3499,
    mrp: 4299,
    rating: 4.8,
    numReviews: 120,
    image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&auto=format&fit=crop&q=80',
    description: 'Hydrodynamic low-profile profile with IQfit 3D goggle seal to prevent leaks and eliminate eye marks during competitive laps.',
  },
  {
    name: 'Decathlon Kipsta 35L Water-Resistant Sports Duffle Bag',
    category: 'sports-accessories',
    brand: 'Decathlon',
    price: 1799,
    mrp: 2499,
    rating: 4.8,
    numReviews: 260,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    description: 'Smart compartment duffel with isolated ventilated shoe pocket, water-resistant base, and convertibility into backpack.',
  },
  {
    name: 'CamelBak Podium Chill 710ml Insulated Bike Bottle',
    category: 'sports-accessories',
    brand: 'CamelBak',
    price: 1990,
    mrp: 2490,
    rating: 4.9,
    numReviews: 155,
    image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=800&auto=format&fit=crop&q=80',
    description: 'Double-walled aerogel insulation keeps water cold twice as long, self-sealing Jet Valve eliminates splatters and leaks.',
  },

  // Mens Shirts & Tops (10 products)
  {
    name: 'Van Heusen Luxury Egyptian Cotton Slim Fit Formal Shirt',
    category: 'mens-shirts',
    brand: 'Van Heusen',
    price: 2499,
    mrp: 3299,
    rating: 4.7,
    numReviews: 210,
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80',
    description: '100% two-ply Egyptian long-staple cotton with silk protein finish, semi-cutaway collar, and French cuffs.',
  },
  {
    name: 'Raymond Custom Tailored Linen Casual Shirt',
    category: 'mens-shirts',
    brand: 'Raymond',
    price: 2999,
    mrp: 3999,
    rating: 4.8,
    numReviews: 165,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80',
    description: 'Pure European flax linen with natural breathable slub texture, relaxed spread collar, and mother-of-pearl buttons.',
  },
  {
    name: 'Tommy Hilfiger Solid Oxford Button-Down Shirt',
    category: 'mens-shirts',
    brand: 'Tommy Hilfiger',
    price: 4999,
    mrp: 6499,
    rating: 4.8,
    numReviews: 190,
    image: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80',
    description: 'Pre-washed garment dyed heavy cotton oxford cloth with signature flag embroidery on chest and curved hem.',
  },
  {
    name: 'Allen Solly Casual Check Cotton Shirt',
    category: 'mens-shirts',
    brand: 'Allen Solly',
    price: 1799,
    mrp: 2399,
    rating: 4.5,
    numReviews: 240,
    image: 'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=800&auto=format&fit=crop&q=80',
    description: 'Vibrant yarn-dyed windowpane check pattern, breathable summer cotton with soft enzyme wash and buttoned cuffs.',
  },
  {
    name: 'Levi’s Barstow Western Denim Snap Button Shirt',
    category: 'mens-shirts',
    brand: 'Levi’s',
    price: 3299,
    mrp: 4199,
    rating: 4.8,
    numReviews: 310,
    image: 'https://images.unsplash.com/photo-1588359348347-9bc6cbbb689e?w=800&auto=format&fit=crop&q=80',
    description: 'Authentic Western shoulder yoke details, pearl snap closures, double flap chest pockets in durable 8oz ring-spun denim.',
  },
  {
    name: 'Zara Man Relaxed Fit Textured Overshirt',
    category: 'tops',
    brand: 'Zara',
    price: 3590,
    mrp: 4590,
    rating: 4.6,
    numReviews: 140,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&auto=format&fit=crop&q=80',
    description: 'Heavy waffle knit boxy overshirt with dropped shoulders, patch front pockets, and tortoiseshell button closure.',
  },
  {
    name: 'H&M Regular Fit Waffle Henley Neck Long Sleeve',
    category: 'tops',
    brand: 'H&M',
    price: 1499,
    mrp: 1999,
    rating: 4.5,
    numReviews: 230,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    description: 'Soft thermal cotton jersey waffle knit with a 3-button placket and ribbed cuffs for effortless off-duty layering.',
  },
  {
    name: 'Calvin Klein Liquid Touch Supima Cotton Polo',
    category: 'tops',
    brand: 'Calvin Klein',
    price: 4499,
    mrp: 5999,
    rating: 4.8,
    numReviews: 180,
    image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80',
    description: 'Silky smooth high-gauge Supima cotton with natural cool-touch drape, ribbed flat-knit collar, and minimal subtle branding.',
  },
  {
    name: 'Uniqlo AIRism Cotton Oversized Crewneck Tee',
    category: 'tops',
    brand: 'Uniqlo',
    price: 1490,
    mrp: 1990,
    rating: 4.9,
    numReviews: 520,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    description: 'Outer cotton layer with inner AIRism moisture-wicking technology for a dry, smooth feel with relaxed drop shoulders.',
  },
  {
    name: 'Marks & Spencer Pure Cotton Non-Iron Striped Shirt',
    category: 'mens-shirts',
    brand: 'Marks & Spencer',
    price: 2799,
    mrp: 3499,
    rating: 4.7,
    numReviews: 160,
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80',
    description: 'Special wrinkle-resistant finish stays crisp through long office days and flights, finished with taped seams for durability.',
  },

  // Mens Shoes (10 products)
  {
    name: 'Nike Air Max 270 React Running Shoes',
    category: 'mens-shoes',
    brand: 'Nike',
    price: 11495,
    mrp: 13995,
    rating: 4.8,
    numReviews: 390,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
    description: 'Largest Max Air unit in heel combined with full-length Nike React foam for unmatched springy bounce and all-day comfort.',
  },
  {
    name: 'Adidas Ultraboost Light Carbon Neutral Runners',
    category: 'mens-shoes',
    brand: 'Adidas',
    price: 14999,
    mrp: 18999,
    rating: 4.9,
    numReviews: 340,
    image: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=800&auto=format&fit=crop&q=80',
    description: '30% lighter Boost material with Primeknit+ adaptive upper and Continental Better Rubber outsole for wet/dry traction.',
  },
  {
    name: 'Clarks Bushacre 3 Leather Chukka Desert Boots',
    category: 'mens-shoes',
    brand: 'Clarks',
    price: 7999,
    mrp: 9999,
    rating: 4.8,
    numReviews: 195,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&auto=format&fit=crop&q=80',
    description: 'Full-grain oiled beeswax leather upper, OrthoLite multi-density footbed, and flexible durable rubber crepe sole.',
  },
  {
    name: 'Puma Velocity Nitro 3 Road Running Shoes',
    category: 'mens-shoes',
    brand: 'Puma',
    price: 6999,
    mrp: 9999,
    rating: 4.7,
    numReviews: 210,
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop&q=80',
    description: 'NITRO advanced nitrogen-injected foam technology providing superior responsiveness in an extremely lightweight package.',
  },
  {
    name: 'Woodland Camel Suede Leather High-Trek Boots',
    category: 'mens-shoes',
    brand: 'Woodland',
    price: 4995,
    mrp: 6495,
    rating: 4.6,
    numReviews: 320,
    image: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&auto=format&fit=crop&q=80',
    description: 'Heavy duty nubuck leather with grooved rubber lug sole designed for high friction on steep rock trails and mud terrain.',
  },
  {
    name: 'New Balance 574 Core Classic Suede Sneakers',
    category: 'mens-shoes',
    brand: 'New Balance',
    price: 7499,
    mrp: 8999,
    rating: 4.8,
    numReviews: 290,
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=80',
    description: 'ENCAP midsole cushioning combines lightweight foam with durable polyurethane rim for all-day arch and heel support.',
  },
  {
    name: 'Cole Haan GrandPrø Tennis Sneaker Hand-Stained Leather',
    category: 'mens-shoes',
    brand: 'Cole Haan',
    price: 11999,
    mrp: 14999,
    rating: 4.8,
    numReviews: 140,
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&auto=format&fit=crop&q=80',
    description: 'Weighs only 8.8 ounces, handcrafted burnished calfskin leather with Grand.ØS ergonomic comfort footbed.',
  },
  {
    name: 'Red Tape Men Genuine Leather Chelsea Ankle Boots',
    category: 'mens-shoes',
    brand: 'Red Tape',
    price: 2499,
    mrp: 5999,
    rating: 4.5,
    numReviews: 410,
    image: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=800&auto=format&fit=crop&q=80',
    description: 'Elasticated side gussets and rear pull loop for slip-on ease, cushioned TPR sole with slip-resistant tread pattern.',
  },
  {
    name: 'Asics Gel-Nimbus 26 Maximum Cushioning Shoes',
    category: 'mens-shoes',
    brand: 'Asics',
    price: 13999,
    mrp: 15999,
    rating: 4.9,
    numReviews: 250,
    image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
    description: 'PureGEL technology and FF BLAST PLUS ECO cushioning create softer landings and cloud-like transitions on marathon distances.',
  },
  {
    name: 'Bata Comfit Lightweight Formal Oxford Derby',
    category: 'mens-shoes',
    brand: 'Bata',
    price: 2199,
    mrp: 2999,
    rating: 4.4,
    numReviews: 270,
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&auto=format&fit=crop&q=80',
    description: 'Deep padded memory cushion collar, synthetic breathable lining, and flexible lightweight polyurethane outsole.',
  },

  // Womens Bags & Dresses (10 products)
  {
    name: 'Coach Willow Polished Pebble Leather Tote Bag',
    category: 'womens-bags',
    brand: 'Coach',
    price: 34500,
    mrp: 39500,
    rating: 4.9,
    numReviews: 160,
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80',
    description: 'Features two open pockets, a secure center zip compartment, and turnlock closure with comfortable shoulder handles.',
  },
  {
    name: 'Michael Kors Jet Set Travel Saffiano Crossbody',
    category: 'womens-bags',
    brand: 'Michael Kors',
    price: 18500,
    mrp: 22000,
    rating: 4.8,
    numReviews: 280,
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80',
    description: 'Durable scratch-resistant Saffiano leather with gold-tone hardware, adjustable chain-link crossbody strap, and top zip closure.',
  },
  {
    name: 'Kate Spade New York Knott Medium Satchel',
    category: 'womens-bags',
    brand: 'Kate Spade',
    price: 28900,
    mrp: 33000,
    rating: 4.8,
    numReviews: 125,
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&auto=format&fit=crop&q=80',
    description: 'Cinched knotted sides, textured pebbled leather with smooth Italian leather trim, multiple organized interior compartments.',
  },
  {
    name: 'Lavie Horizontal Structured Laptop Tote for Women',
    category: 'womens-bags',
    brand: 'Lavie',
    price: 2499,
    mrp: 4999,
    rating: 4.5,
    numReviews: 320,
    image: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&auto=format&fit=crop&q=80',
    description: 'Padded sleeve fits laptops up to 15.6 inches, dedicated water bottle holder, key leash, and premium gold metal accents.',
  },
  {
    name: 'Baggit Cruelty-Free Vegan Leather Shoulder Bag',
    category: 'womens-bags',
    brand: 'Baggit',
    price: 1890,
    mrp: 2990,
    rating: 4.6,
    numReviews: 240,
    image: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800&auto=format&fit=crop&q=80',
    description: 'PETA-approved sustainable vegan faux leather with dual zipper chambers and quick-access back slit smartphone pocket.',
  },
  {
    name: 'AND Floral Chiffon A-Line Midi Dress',
    category: 'womens-dresses',
    brand: 'AND',
    price: 2799,
    mrp: 3999,
    rating: 4.7,
    numReviews: 190,
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&auto=format&fit=crop&q=80',
    description: 'Fluid lightweight georgette chiffon with subtle tiered ruffles, sweetheart neckline, and flattering smocked back bodice.',
  },
  {
    name: 'Fabindia Pure Silk Handblock Printed Kurta Set',
    category: 'womens-dresses',
    brand: 'Fabindia',
    price: 6990,
    mrp: 8490,
    rating: 4.9,
    numReviews: 150,
    image: 'https://images.unsplash.com/photo-1618244972963-dbee1a7edc95?w=800&auto=format&fit=crop&q=80',
    description: 'Pure Chanderi silk with artisan Bagru hand block floral motifs, delicate zari embroidery on the yoke, paired with matching pants.',
  },
  {
    name: 'Mango Belted Pleated Shirt Dress with Pockets',
    category: 'womens-dresses',
    brand: 'Mango',
    price: 4590,
    mrp: 5990,
    rating: 4.6,
    numReviews: 110,
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&auto=format&fit=crop&q=80',
    description: 'Contemporary structured poplin cotton shirt dress with detachable fabric belt, turn-up sleeves, and side split hem.',
  },
  {
    name: 'W for Woman Gold Print Anarkali Festive Dress',
    category: 'womens-dresses',
    brand: 'W',
    price: 3499,
    mrp: 4999,
    rating: 4.7,
    numReviews: 215,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80',
    description: 'Full flare Anarkali silhouette with metallic foil accents, round neck with keyhole detail, and three-quarter churidar sleeves.',
  },
  {
    name: 'Zara Satin Finish Slip Dress with V-Neck',
    category: 'womens-dresses',
    brand: 'Zara',
    price: 2990,
    mrp: 3990,
    rating: 4.8,
    numReviews: 175,
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&auto=format&fit=crop&q=80',
    description: 'Lustrous heavyweight satin with bias cut drape that skims the silhouette, delicate adjustable spaghetti straps, side slit.',
  },

  // Remaining 20 products for full 100 items across core categories
  // Mobile Accessories (5 more)
  {
    name: 'Keychron K2 Pro QMK/VIA Wireless Mechanical Keyboard',
    category: 'mobile-accessories',
    brand: 'Keychron',
    price: 8999,
    mrp: 10999,
    rating: 4.9,
    numReviews: 210,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    description: '75% compact layout, hot-swappable Keychron K Pro Red switches, sound-absorbing foam, Mac/Windows layout switch.',
  },
  {
    name: 'Logitech MX Master 3S Ergonomic Wireless Mouse',
    category: 'mobile-accessories',
    brand: 'Logitech',
    price: 8995,
    mrp: 10995,
    rating: 4.9,
    numReviews: 480,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
    description: 'MagSpeed electromagnetic scroll wheel, 8K DPI any-surface glass tracking, Quiet Clicks technology, USB-C fast charging.',
  },
  {
    name: 'SanDisk Extreme 1TB Portable SSD 1050MB/s USB-C',
    category: 'mobile-accessories',
    brand: 'SanDisk',
    price: 9499,
    mrp: 14999,
    rating: 4.8,
    numReviews: 350,
    image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80',
    description: 'Rugged rubberized chassis with IP55 water and dust resistance, 2-meter drop protection, and handy carabiner loop.',
  },
  {
    name: 'CalDigit TS4 Thunderbolt 4 18-Port Docking Station',
    category: 'mobile-accessories',
    brand: 'CalDigit',
    price: 36990,
    mrp: 41990,
    rating: 4.9,
    numReviews: 75,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    description: 'Industry-standard 18 ports of connectivity with 98W Power Delivery to charge your laptop at maximum speed.',
  },
  {
    name: 'Elgato Stream Deck MK.2 with 15 Customizable LCD Keys',
    category: 'mobile-accessories',
    brand: 'Elgato',
    price: 13999,
    mrp: 16999,
    rating: 4.8,
    numReviews: 190,
    image: 'https://images.unsplash.com/photo-1547394765-185e1317ac14?w=800&auto=format&fit=crop&q=80',
    description: 'Trigger actions in apps, control studio audio, adjust smart lights, and launch shortcuts with one tactile tap.',
  },

  // Sports Accessories (5 more)
  {
    name: 'Garmin HRM-Pro Plus Heart Rate Monitor Strap',
    category: 'sports-accessories',
    brand: 'Garmin',
    price: 11990,
    mrp: 13990,
    rating: 4.9,
    numReviews: 120,
    image: 'https://images.unsplash.com/photo-1510519138161-5844da972bf7?w=800&auto=format&fit=crop&q=80',
    description: 'Transmits real-time heart rate data over ANT+ and BLUETOOTH Low Energy, captures running dynamics and pace for indoor treadmills.',
  },
  {
    name: 'Therabody Theragun Mini 2.0 Percussive Massage Gun',
    category: 'sports-accessories',
    brand: 'Therabody',
    price: 16999,
    mrp: 19999,
    rating: 4.8,
    numReviews: 180,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    description: 'Ultra-portable deep tissue muscle therapy with proprietary brushless motor and QuietForce sound insulation.',
  },
  {
    name: 'Bowflex SelectTech 552 Adjustable Dumbbells (Pair)',
    category: 'sports-accessories',
    brand: 'Bowflex',
    price: 34990,
    mrp: 42000,
    rating: 4.9,
    numReviews: 110,
    image: 'https://images.unsplash.com/photo-1586401100454-05cb9bcf5cb8?w=800&auto=format&fit=crop&q=80',
    description: 'Replaces 15 sets of weights, adjust from 2.5 to 24 kg with the turn of a dial, quiet molding for smooth lifts.',
  },
  {
    name: 'Hydro Flask 32oz Wide Mouth with Flex Straw Cap',
    category: 'sports-accessories',
    brand: 'Hydro Flask',
    price: 3999,
    mrp: 4799,
    rating: 4.9,
    numReviews: 310,
    image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=800&auto=format&fit=crop&q=80',
    description: 'TempShield double-wall vacuum insulation keeps beverages ice cold for up to 24 hours without condensation.',
  },
  {
    name: 'Grip Strength Trainer Kit with Finger Exerciser',
    category: 'sports-accessories',
    brand: 'Boldfit',
    price: 699,
    mrp: 1199,
    rating: 4.6,
    numReviews: 420,
    image: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800&auto=format&fit=crop&q=80',
    description: 'Adjustable resistance from 10 to 60 kg with mechanical rep counter for forearm development and rehabilitation.',
  },

  // Mens Watches (5 more)
  {
    name: 'Titan Edge Ceramic Ultra-Slim Watch',
    category: 'mens-watches',
    brand: 'Titan',
    price: 24995,
    mrp: 27995,
    rating: 4.8,
    numReviews: 130,
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&auto=format&fit=crop&q=80',
    description: 'One of the slimmest ceramic watches in the world at 4.4mm with sapphire crystal and scratch-proof high-tech ceramic bracelet.',
  },
  {
    name: 'Citizen Tsuyosa Automatic Amber Yellow Dial',
    category: 'mens-watches',
    brand: 'Citizen',
    price: 32000,
    mrp: 36000,
    rating: 4.9,
    numReviews: 175,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
    description: 'Vibrant sunray dial with integrated stainless steel presidential bracelet, date magnifier, and see-through exhibition caseback.',
  },
  {
    name: 'Diesel Mega Chief Chronograph Gunmetal Stainless Watch',
    category: 'mens-watches',
    brand: 'Diesel',
    price: 18495,
    mrp: 21995,
    rating: 4.6,
    numReviews: 210,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    description: 'Commanding 51mm case with signature "Only The Brave" dial crown clip, iridescent crystal, and chronograph stopwatch.',
  },
  {
    name: 'Casio Edifice Solar Powered Chronograph Sapphire',
    category: 'mens-watches',
    brand: 'Casio',
    price: 13995,
    mrp: 16995,
    rating: 4.7,
    numReviews: 190,
    image: 'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=800&auto=format&fit=crop&q=80',
    description: 'Slim solar-powered chronograph with scratch-resistant sapphire crystal and carbon fiber patterned dial.',
  },
  {
    name: 'Seiko 5 Sports Automatic Military Flieger Green Dial',
    category: 'mens-watches',
    brand: 'Seiko',
    price: 23500,
    mrp: 26000,
    rating: 4.8,
    numReviews: 240,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80',
    description: 'Pilot field watch with day/date display, LumiBrite hands, 4R36 automatic caliber with manual winding and hacking.',
  },

  // Sunglasses (5 more)
  {
    name: 'Ray-Ban Clubmaster Classic Browline Sunglasses',
    category: 'sunglasses',
    brand: 'Ray-Ban',
    price: 10490,
    mrp: 12200,
    rating: 4.9,
    numReviews: 260,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80',
    description: 'Retro 1950s browline styling with black acetate upper, polished gold metal lower rim, and classic G-15 glass lenses.',
  },
  {
    name: 'Oakley Frogskins 35th Anniversary Edition',
    category: 'sunglasses',
    brand: 'Oakley',
    price: 9290,
    mrp: 10800,
    rating: 4.7,
    numReviews: 140,
    image: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=800&auto=format&fit=crop&q=80',
    description: 'Tribute to 1980s pop culture with classic Frogskin metal hinge, lightweight O Matter frame, and Prizm Violet mirror lenses.',
  },
  {
    name: 'Maui Jim Red Sands Polarized Lightweight Rectangle',
    category: 'sunglasses',
    brand: 'Maui Jim',
    price: 18900,
    mrp: 21500,
    rating: 4.9,
    numReviews: 110,
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80',
    description: 'Refined rectangular silhouette crafted with thin injected nylon and MauiPure lenses for crispest scratch-resistant clarity.',
  },
  {
    name: 'Fastrack Sporty Wrap Sunglasses UV Protection',
    category: 'sunglasses',
    brand: 'Fastrack',
    price: 1895,
    mrp: 2495,
    rating: 4.4,
    numReviews: 310,
    image: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=800&auto=format&fit=crop&q=80',
    description: 'Dynamic sports styling with aerodynamic side air vents to prevent fogging during morning marathons and bike rides.',
  },
  {
    name: 'Vincent Chase Polarized Aviator Golden Frame',
    category: 'sunglasses',
    brand: 'Vincent Chase',
    price: 1299,
    mrp: 2299,
    rating: 4.5,
    numReviews: 340,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80',
    description: 'Classic teardrop aviator with spring temples, soft silicone nose pads, and polarized green lenses.',
  },
];

export async function insertMoreProducts() {
  console.log('Connecting to MongoDB...');
  await mongoose.connect(env.MONGO_URI, { dbName: 'shopnest' });
  console.log('Connected.');

  const countBefore = await Product.countDocuments();
  console.log(`Current product count before insertion: ${countBefore}`);

  const docs = additionalProducts.map((p, idx) => {
    const cleanSlug = `${p.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')}-${Date.now()}-${idx + 1}`;

    return {
      name: p.name,
      slug: cleanSlug,
      description: p.description,
      price: p.price,
      mrp: p.mrp,
      category: p.category,
      brand: p.brand,
      stock: 30,
      rating: p.rating,
      numReviews: p.numReviews,
      image: p.image,
      images: [p.image],
      isFeatured: p.rating >= 4.8,
      inStock: true,
    };
  });

  console.log(`Inserting ${docs.length} more products into MongoDB...`);
  const result = await Product.insertMany(docs);
  console.log(`Successfully inserted ${result.length} new products!`);

  const countAfter = await Product.countDocuments();
  console.log(`New total product count in DB: ${countAfter}`);

  await mongoose.disconnect();
  console.log('Done.');
}

insertMoreProducts();
